name: llm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - anyio=4.6.2.post1
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=24.2.0
  - babel=2.16.0
  - beautifulsoup4=4.12.3
  - bleach=6.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cffi=1.17.1
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.11.10
  - debugpy=1.8.8
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - fqdn=1.5.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpx=0.27.2
  - hyperframe=6.0.1
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - ipykernel=6.29.5
  - ipython=8.29.0
  - isoduration=20.11.0
  - jedi=0.19.2
  - json5=0.9.28
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.3.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - lz4-c=1.9.4
  - matplotlib-inline=0.1.7
  - mistune=3.0.2
  - nbclient=0.10.0
  - nbconvert-core=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook-shim=0.2.4
  - openssl=3.4.0
  - overrides=7.7.0
  - packaging=24.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.6
  - prometheus_client=0.21.0
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.11.10
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytz=2024.2
  - pywin32=307
  - pywinpty=2.0.14
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.21.0
  - send2trash=1.8.3
  - setuptools=75.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.2
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.1.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241003
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - ucrt=10.0.22621.0
  - uri-template=1.3.0
  - urllib3=2.2.3
  - vc=14.40
  - vc14_runtime=14.40.33810
  - vs2015_runtime=14.40.33810
  - wcwidth=0.2.13
  - webcolors=24.8.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.11.0
      - aiosignal==1.3.1
      - altair==5.4.1
      - annotated-types==0.7.0
      - asgiref==3.8.1
      - backoff==2.2.1
      - bcrypt==4.2.0
      - blinker==1.9.0
      - build==1.2.2.post1
      - cachetools==5.5.0
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.18
      - click==8.1.7
      - coloredlogs==15.0.1
      - contourpy==1.3.1
      - cryptography==43.0.3
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - deprecated==1.2.14
      - docarray==0.40.0
      - durationpy==0.9
      - fastapi==0.115.5
      - filelock==3.13.1
      - flatbuffers==24.3.25
      - fonttools==4.55.0
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.36.0
      - googleapis-common-protos==1.66.0
      - greenlet==3.1.1
      - grpcio==1.67.1
      - httpcore==1.0.6
      - httptools==0.6.4
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.2
      - humanfriendly==10.0
      - idna==3.4
      - jinja2==3.1.3
      - jsonpatch==1.33
      - kiwisolver==1.4.7
      - kubernetes==31.0.0
      - langchain==0.3.7
      - langchain-community==0.3.7
      - langchain-core==0.3.18
      - langchain-ollama==0.2.0
      - langchain-text-splitters==0.3.2
      - langsmith==0.1.143
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - marshmallow==3.23.1
      - matplotlib==3.9.2
      - mdurl==0.1.2
      - mmh3==5.0.1
      - monotonic==1.6
      - mpmath==1.3.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.13.5
      - networkx==3.2.1
      - numpy==1.26.3
      - oauthlib==3.2.2
      - ollama==0.3.3
      - onnxruntime==1.20.0
      - opentelemetry-api==1.28.1
      - opentelemetry-exporter-otlp-proto-common==1.28.1
      - opentelemetry-exporter-otlp-proto-grpc==1.28.1
      - opentelemetry-instrumentation==0.49b1
      - opentelemetry-instrumentation-asgi==0.49b1
      - opentelemetry-instrumentation-fastapi==0.49b1
      - opentelemetry-proto==1.28.1
      - opentelemetry-sdk==1.28.1
      - opentelemetry-semantic-conventions==0.49b1
      - opentelemetry-util-http==0.49b1
      - orjson==3.10.11
      - pandas==2.2.3
      - pdfminer-six==20240706
      - pillow==10.2.0
      - posthog==3.7.0
      - propcache==0.2.0
      - protobuf==5.28.3
      - pyarrow==18.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pydantic-settings==2.6.1
      - pydeck==0.9.1
      - pyparsing==3.2.0
      - pypdf==5.1.0
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pyreadline3==3.5.4
      - python-dotenv==1.0.1
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - shellingham==1.5.4
      - smmap==5.0.1
      - sqlalchemy==2.0.35
      - starlette==0.41.2
      - streamlit==1.40.1
      - sympy==1.13.1
      - tenacity==9.0.0
      - tokenizers==0.20.3
      - toml==0.10.2
      - tqdm==4.67.0
      - typer==0.13.0
      - types-requests==2.32.0.20241016
      - typing-extensions==4.10.0
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - uvicorn==0.32.0
      - watchdog==6.0.0
      - watchfiles==0.24.0
      - websockets==14.1
      - wrapt==1.16.0
      - yarl==1.17.1
